DROP TABLE IF EXISTS INDICE;
DROP TABLE IF EXISTS Stock;
CREATE TABLE INDICE (
  INDICE_ID INT AUTO_INCREMENT  PRIMARY KEY,
  INDICE1 VARCHAR(20) NOT NULL,
  EXCHNG_CODE VARCHAR(20) NOT NULL
);

CREATE TABLE Stock (
  STOCK_ID INT AUTO_INCREMENT  PRIMARY KEY,
  ISIN_CODE VARCHAR(20) NOT NULL,
  SYMBOL VARCHAR(20) NOT NULL,
  COMPANY_NAME VARCHAR(100) NOT NULL,
  INDICE_ID INT,
  FOREIGN KEY(INDICE_ID) REFERENCES Indice(INDICE_ID),
  CONSTRAINT STOCK_INFO UNIQUE(INDICE_ID,ISIN_CODE)
);
